max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
format_generated_files = false 