[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
array_protocol = "3mGJZ2tU1Pgnhdy7gN2YRh6eFutwAGxezUmjrDUJFcts"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
