[workspace]
members = [
    "programs/*"
]
exclude = [
    "utils/account-extractor"
]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
overflow-checks = true

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1